<div class="container" style="margin-top: 4em;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <a href="<?= $this->url('client', ['controller' => 'Index', 'action' => 'index']); ?>" class="btn text-left ml-3">
                    Voltar
                </a>
                <div class="card-body">
                    <h3 class="card-title mb-4 text-center">Cadastrar cliente</h3>
                    <?php
                    echo $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible']);
                    echo $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible']);
                    ?>

                    <?= $this->form()->openTag($this->form); ?>

                    <div class="form-group <?= $this->formElementErrors($this->form->get('name')) ? 'has-error' : ''; ?> has-feedback">
                        <?= $this->formLabel($this->form->get('name')); ?>
                        <?= $this->formText($this->form->get('name')); ?>
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                        <?= $this->formElementErrors($this->form->get('name')); ?>
                    </div>
                    <div class="form-row">
                        <div class="form-group col <?= $this->formElementErrors($this->form->get('cpf_cnpj')) ? 'has-error' : ''; ?> has-feedback">
                            <?= $this->formLabel($this->form->get('cpf_cnpj')); ?>
                            <?= $this->formText($this->form->get('cpf_cnpj')); ?>
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                            <?= $this->formElementErrors($this->form->get('cpf_cnpj')); ?>
                        </div>
                        <div class="form-group col  <?= $this->formElementErrors($this->form->get('rg_ie')) ? 'has-error' : ''; ?> has-feedback">
                            <?= $this->formLabel($this->form->get('rg_ie')); ?>
                            <?= $this->formText($this->form->get('rg_ie')); ?>
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                            <?= $this->formElementErrors($this->form->get('rg_ie')); ?>
                        </div>

                    </div>
                    <div class="form-row">
                        <div class="form-group col <?= $this->formElementErrors($this->form->get('uf')) ? 'has-error' : ''; ?> has-feedback">
                            <?= $this->formLabel($this->form->get('uf')); ?>
                            <?= $this->formText($this->form->get('uf')); ?>
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                            <?= $this->formElementErrors($this->form->get('uf')); ?>
                        </div>
                        <div class="form-group col <?= $this->formElementErrors($this->form->get('city')) ? 'has-error' : ''; ?> has-feedback">
                            <?= $this->formLabel($this->form->get('city')); ?>
                            <?= $this->formText($this->form->get('city')); ?>
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                            <?= $this->formElementErrors($this->form->get('city')); ?>
                        </div>
                    </div>
                    <div class="form-group <?= $this->formElementErrors($this->form->get('address')) ? 'has-error' : ''; ?> has-feedback">
                        <?= $this->formLabel($this->form->get('address')); ?>
                        <?= $this->formText($this->form->get('address')); ?>
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                        <?= $this->formElementErrors($this->form->get('address')); ?>
                    </div>

                    <?= $this->formHidden($this->form->get('csrf')); ?>
                    <?= $this->formHidden($this->form->get('id')); ?>
                    <div class="form-group">
                        <div class="pull-right col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Alterar</button>
                        </div>
                    </div>
                    <?= $this->form()->closeTag(); ?>

                    <a href="<?= $this->url('client', ['controller' => 'Index', 'action' => 'index']); ?>" class="text-center">
                        Acessar clientes cadastrados
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>