<?php
$title = 'Cliente';
$this->headTitle($title);
?>

<div class="container" style="margin-top: 4em;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <a href="<?= $this->url('client', ['controller' => 'Index', 'action' => 'index']); ?>" class="btn text-left ml-3 col-md-2">
                    Voltar
                </a>
                <div class="card-body">
                    <h3 class="card-title mb-4 text-center"><?= $this->escapeHtml('Editar ' . $title) ?></h3>
                    <?php
                    echo $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible']);
                    echo $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible']);
                    ?>

                    <?= $this->form()->openTag($this->form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($this->form->get('name')); ?>
                        <?= $this->formText($this->form->get('name')); ?>
                        <?= $this->formElementErrors($this->form->get('name')); ?>
                    </div>
                    <div class="form-row">
                        <div class="form-group col">
                            <?= $this->formLabel($this->form->get('cpf_cnpj')); ?>
                            <?= $this->formText($this->form->get('cpf_cnpj')); ?>
                            <?= $this->formElementErrors($this->form->get('cpf_cnpj')); ?>
                        </div>
                        <div class="form-group col">
                            <?= $this->formLabel($this->form->get('rg_ie')); ?>
                            <?= $this->formText($this->form->get('rg_ie')); ?>
                            <?= $this->formElementErrors($this->form->get('rg_ie')); ?>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col">
                            <?= $this->formLabel($this->form->get('uf')); ?>
                            <?= $this->formText($this->form->get('uf')); ?>
                            <?= $this->formElementErrors($this->form->get('uf')); ?>
                        </div>
                        <div class="form-group col">
                            <?= $this->formLabel($this->form->get('city')); ?>
                            <?= $this->formText($this->form->get('city')); ?>
                            <?= $this->formElementErrors($this->form->get('city')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($this->form->get('address')); ?>
                        <?= $this->formText($this->form->get('address')); ?>
                        <?= $this->formElementErrors($this->form->get('address')); ?>
                    </div>
                    <?= $this->formHidden($this->form->get('csrf')); ?>
                    <?= $this->formHidden($this->form->get('id')); ?>
                    <div class="form-group">
                        <div class="pull-right col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Alterar</button>
                        </div>
                    </div>
                    <?= $this->form()->closeTag(); ?>

                    <a href="<?= $this->url('client', ['controller' => 'Index', 'action' => 'index']); ?>" class="text-center btn-block ">
                        Acessar clientes cadastrados
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#cpf_cnpj').inputmask({
            mask: ['999.999.999-99', '99.999.999/9999-99'],
            keepStatic: true,
            placeholder: ''
        });

        $('#rg_ie').inputmask({
            mask: ['999999999', '99.999.999/9999-99'],
            keepStatic: true,
            placeholder: ''
        });
    });
</script>