<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title mb-4 text-center">Login</h3>
                    <?php
                    echo $this->flashMessenger()->render('error', ['alert alert-danger alert-dismissible']);
                    echo $this->flashMessenger()->render('info', ['alert alert-info alert-dismissible']);
                    ?>

                    <?php echo $this->form()->openTag($this->form); ?>
                    <div class="form-group<?php echo $this->formElementErrors($this->form->get('email')) ? ' has-error' : ''; ?> has-feedback">
                        <?php echo $this->formEmail($this->form->get('email')); ?>
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                        <?php echo $this->formElementErrors($this->form->get('email')); ?>
                    </div>

                    <div class="form-group<?php echo $this->formElementErrors($this->form->get('password')) ? ' has-error' : ''; ?> has-feedback">
                        <?php echo $this->formPassword($this->form->get('password')); ?>
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                        <?php echo $this->formElementErrors($this->form->get('password')); ?>
                    </div>
                    <?php echo $this->formHidden($this->form->get('csrf'));  ?>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Logar</button>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                    <a href="<?= $this->url('user/default', ['controller' => 'Index', 'action' => 'register']); ?>" class="text-center">Criar registro</a>
                </div>
            </div>
        </div>
    </div>
</div>