<div class="container">
    <h1 class="text-center mb-4">Protocolo <?= (int) $this->protocol->id ?></h1>

    <div class="row">
        <div class="col-sm-6">
            <p><strong>Requerente:</strong> <?= $this->protocol->applicant ?></p>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <p class="mb-4"><strong>Assunto:</strong></p>
            <p><?= $this->protocol->subject ?></p>
        </div>
    </div>
</div>