<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title mb-4 text-center">Registrar novo membro</h3>

                    <?php
                    echo $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible']);
                    echo $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible']);
                    ?>

                    <?= $this->form()->openTag($this->form); ?>
                    <div class="form-group">
                        <?= $this->formLabel($this->form->get('name')); ?>
                        <?= $this->formText($this->form->get('name')); ?>
                        <?= $this->formElementErrors($this->form->get('name')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($this->form->get('email')); ?>
                        <?= $this->formEmail($this->form->get('email')); ?>
                        <?= $this->formElementErrors($this->form->get('email')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($this->form->get('password')); ?>
                        <?= $this->formPassword($this->form->get('password')); ?>
                        <?= $this->formElementErrors($this->form->get('password')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($this->form->get('verifyPassword')); ?>
                        <?= $this->formPassword($this->form->get('verifyPassword')); ?>
                        <?= $this->formElementErrors($this->form->get('verifyPassword')); ?>
                    </div>
                    <?= $this->formHidden($this->form->get('csrf')); ?>
                    <div class="form-group">
                        <div class="pull-right col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Registrar</button>
                        </div>
                    </div>
                    <?= $this->form()->closeTag(); ?>

                    <a href="<?= $this->url('auth.login'); ?>" class="text-center">
                        Eu já tenho cadastro
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>