<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-5">
    <div class="card-deck d-flex justify-content-center">
        <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header text-center">Clientes</div>
            <div class="card-body">
                <h4 class="card-title text-center"><?= $clients ?></h4>
                <p class="card-text text-center">Cadastrados</p>
            </div>
        </div>

        <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header text-center">Protocolos</div>
            <div class="card-body">
                <h4 class="card-title text-center"><?= $protocols ?></h4>
                <p class="card-text text-center">Cadastrados</p>
            </div>
        </div>
    </div>
</main>