<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Clientes</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <button type="button" class="btn btn-sm btn-outline-secondary">Novo Cliente</button>
        </div>
    </div>
    <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Cliente 1
            <div>
                <button type="button" class="btn btn-sm btn-outline-secondary mr-2">Editar</button>
                <button type="button" class="btn btn-sm btn-outline-danger">Excluir</button>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Cliente 2
            <div>
                <button type="button" class="btn btn-sm btn-outline-secondary mr-2">Editar</button>
                <button type="button" class="btn btn-sm btn-outline-danger">Excluir</button>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Cliente 3
            <div>
                <button type="button" class="btn btn-sm btn-outline-secondary mr-2">Editar</button>
                <button type="button" class="btn btn-sm btn-outline-danger">Excluir</button>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Cliente 3
            <div>
                <button type="button" class="btn btn-sm btn-outline-secondary mr-2">Editar</button>
                <button type="button" class="btn btn-sm btn-outline-danger">Excluir</button>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Cliente 3
            <div>
                <button type="button" class="btn btn-sm btn-outline-secondary mr-2">Editar</button>
                <button type="button" class="btn btn-sm btn-outline-danger">Excluir</button>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Cliente 3
            <div>
                <button type="button" class="btn btn-sm btn-outline-secondary mr-2">Editar</button>
                <button type="button" class="btn btn-sm btn-outline-danger">Excluir</button>
            </div>
        </li>
    </ul>
</main>