<?php
$title = 'Protocolo';
$this->headTitle($title);

?>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Protocolos</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="<?= $this->url('protocol', ['controller' => 'Index', 'action' => 'register']); ?>" class="btn btn-sm btn-outline-secondary">Novo Protocolo</a>
        </div>
    </div>
    <ul class="list-group">
        <?php

        foreach ($paginator as $protocol) :
        ?>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <?= $this->escapeHtml((int) $protocol->id) ?>
                </div>
                <div>
                    <?= $this->escapeHtml($protocol->applicant) ?>
                </div>
                <div>
                    <?= $this->escapeHtml($protocol->cpf_cnpj) ?>
                </div>
                <div>
                    <a target="_blank" href="<?= $this->url('protocol', ['controller' => 'Index', 'action' => 'print', 'id' => $protocol->id]); ?>" class=" btn btn-sm btn-outline-secondary">Imprimir</a>
                    <a href="<?= $this->url('protocol', ['controller' => 'Index', 'action' => 'edit', 'id' => $protocol->id]); ?>" class="btn btn-sm btn-outline-info mr-2">Editar</a>
                    <a href="<?= $this->url('protocol', ['controller' => 'Index', 'action' => 'delete', 'id' => $protocol->id]); ?>" class=" btn btn-sm btn-outline-danger">Excluir</a>
                </div>
            </li>
        <?php
        endforeach;
        ?>
    </ul>
</main>