<?php
$title = 'Protocolo';
$this->headTitle($title);
?>

<div class="container" style="margin-top: 4em;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <a href="<?= $this->url('client', ['controller' => 'Index', 'action' => 'index']); ?>" class="btn text-left ml-3 col-md-2">
                    Voltar
                </a>
                <div class="card-body">
                    <h3 class="card-title mb-4 text-center"><?= $this->escapeHtml('Cadastrar ' . $title) ?></h3>
                    <?php
                    echo $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible']);
                    echo $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible']);
                    ?>

                    <?= $this->form()->openTag($this->form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($this->form->get('applicant')); ?>
                        <div class="input-group-prepend">
                            <?= $this->formText($this->form->get('applicant')); ?>
                            <span class="input-group-text btn btn-primary" id="inputGroupPrepend">&telrec;</span>
                        </div>
                        <?= $this->formElementErrors($this->form->get('applicant')); ?>
                    </div>
                    <div class="form-group ">
                        <?= $this->formLabel($this->form->get('cpf_cnpj')); ?>
                        <?= $this->formText($this->form->get('cpf_cnpj')); ?>
                        <?= $this->formElementErrors($this->form->get('cpf_cnpj')); ?>
                    </div>
                    <div class="form-group ">
                        <?= $this->formLabel($this->form->get('subject')); ?>
                        <?= $this->formTextarea($this->form->get('subject')); ?>
                        <?= $this->formElementErrors($this->form->get('subject')); ?>
                    </div>
                    <?= $this->formHidden($this->form->get('csrf')); ?>
                    <?= $this->formHidden($this->form->get('id')); ?>
                    <div class="form-group">
                        <div class="pull-right col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Cadastrar</button>
                        </div>
                    </div>
                    <?= $this->form()->closeTag(); ?>

                    <a href="<?= $this->url('protocol', ['controller' => 'Index', 'action' => 'index']); ?>" class="text-center btn-block">
                        Acessar protocolos cadastrados
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Clientes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body">
                <table id="tabela" class="table table-striped">
                    <thead>
                        <tr>
                            <th>Requerente</th>
                            <th>CPF/CNPJ</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<script>
    fetch('/client/data/').then(function(response) {
        return response.json()
    }).then(function(response) {
        $('#tabela').DataTable({
            data: response,
            autoWidth: false,
            columns: [{
                    data: 'name'
                },
                {
                    data: 'cpf_cnpj'
                }
            ],
            columnDefs: [{
                "defaultContent": "-",
                "targets": "_all"
            }]
        });
    });

    $(document).ready(function() {
        $('#protocol').attr('ng-non-bindable', '');

        $('#tabela tbody').on('dblclick', 'tr', function() {
            let applicant = $(this).find('td:eq(0)').text();
            let cpf_cnpj = $(this).find('td:eq(1)').text();

            $('#applicant')[0].value = applicant;
            $('#cpf_cnpj')[0].value = cpf_cnpj;

            $('#modal').modal('hide');
        });

        $('#inputGroupPrepend').click(function() {
            $('#modal').modal('show');
        });

        $('#cpf_cnpj').inputmask({
            mask: ['999.999.999-99', '99.999.999/9999-99'],
            keepStatic: true,
            placeholder: ''
        });
    });
</script>